name: Build & deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install NPM dependencies
        run: npm install

      - name: Run build task
        run: npm run build

      - name: Deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/srv/53.asteriski.fi/"
          EXCLUDE: "/node_modules/, /.git/, db.sqlite3"
        with:
          ARGS: "--delete"
          SCRIPT_AFTER: |
            sudo /root/.nvm/versions/node/v18.16.0/bin/pm2 restart sveltekit-app
